version: '3.3'
services:

  # nginx reverseproxy http://weablelocal.com
  container_nginx_reverseproxy:
    build:
      context: ./Nginx
      dockerfile: Dockerfile
    image: nginx:1.15-custom
    restart: always
    container_name: container_nginx_reverseproxy
    volumes:
      - ./Nginx/reverseproxy:/etc/nginx/nginxconf.d
    ports:
      - "80:80"
      - "443:443"
    networks:
      - weable_tms_network

  # dotnetcore web
  container_dotnetcore_web:
    build:
      context: .
      dockerfile: Web_Dockerfile
    image: aspnetcore:2.2-custom
    restart: always
    container_name: container_dotnetcore_web
    expose:
      - "80"
    # ports: # comment "ports" use nginx reverseproxy
    #   - "5000:80"
    #   - "5443:443"
    depends_on:
      - container_maria_db
    networks:
      - weable_tms_network

  # dotnetcore web backoffice
  container_dotnetcore_bo_web:
    build:
      context: .
      dockerfile: BO_Web_Dockerfile
    image: aspnetcore:2.2-custom
    restart: always
    container_name: container_dotnetcore_bo_web
    expose:
      - "80"
    # ports: # comment "ports" use nginx reverseproxy
    #   - "5000:80"
    #   - "5443:443"
    depends_on:
      - container_maria_db
    networks:
      - weable_tms_network

  # maria db
  container_maria_db:
    image: mariadb
    restart: always
    container_name: container_maria_db
    environment:
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    expose:
      - "3306"
    # ports: # comment "ports" use nginx reverseproxy
    #   - '3306:3306'
    networks:
      - weable_tms_network

  # phpmyadmin
  container_phpmyadmin:
    depends_on:
      - container_maria_db
    build:
      context: ./Phpmyadmin
      dockerfile: Dockerfile
    image: phpmyadmin-custom
    restart: always
    container_name: container_phpmyadmin
    expose:
      - "80"
    # ports: # comment "ports" use nginx reverseproxy
    #   - '9000:80'
    environment:
      # comment "PMA_ABSOLUTE_URI" use base webserver
      PMA_ABSOLUTE_URI: "http://container_phpmyadmin:80/phpmyadmin/"
      PMA_HOST: container_maria_db
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: weable
      MYSQL_PASSWORD: weable
    networks:
      - weable_tms_network
networks:
  weable_tms_network: